baseurl = "https://cruisemaniac.com/"
googleAnalytics = ""
hasCJKLanguage = false
languageCode = "en-US"
title = "cruisemaniac.com"
[params]
about = ""
author = "Ashwin M"
bio = "Setting servers on fire for over a decade now!"
copyright = ""
customCSS = ["css/custom.css"]
customJS = []
description = "DevOps, Infra and Cloud Expert"
disqusShortname = ""
enableDisqus = false
enableGoogleAnalytics = false
enableNewsletter = true
enableRSS = true
enableShare = false
enableSummary = true
enableToc = false
enableTwitterCard = true
githubRepo = "cruisemaniac"
home = ""
iconFont = "font-awesome"
newerPosts = "Newer"
olderPosts = "Older"
post = ""
readMore = "Here's the latest scoop..."
share = "Facebook"
showLatestPosts = false
socialIconStyle = "rounded"
subscribe = "RSS"
subtitle404 = "You entered the wrong room my friend! Go back ?"
tags = ""
title404 = "Oops! This is a 404."
tweet = "Twitter"
twitter = "cruisemaniac"
twitterCardImage = "images/avatar.jpg"
useDescriptionReplaceSummary = true
[permalinks]
posts = "/post/:title/"
[social]
github-square = "https://github.com/cruisemaniac"
linkedin-square = "https://linkedin.com/in/ashwinmurali"
twitter-square = "https://twitter.com/cruisemaniac"
